name: Release
run-name: Release '${{ github.ref_name }}'
on:
  release:
    types: [published]
env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
  GIT_COMMIT: ${{ github.sha }}
  GIT_URL: ${{ github.repositoryUrl }}
  BUILD_NUMBER: ${{ github.run_number }}
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v5
    - name: JDK 21
      uses: actions/setup-java@v5
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Set version
      run: bash scripts/set-version.sh ci
    - name: Build with Maven
      run: xvfb-run -- mvn -B package
    - name: Upload artifacts
      run: |
           gh release upload ${{github.event.release.tag_name}} \
             build/artifacts/alef-distribution/alef-windows.zip \
             build/artifacts/alef-distribution/alef-MacOSaarch64.zip \
             build/artifacts/alef-distribution/alef-linux.tar.gz
      env:
        GITHUB_TOKEN: ${{ github.TOKEN }}
    - name: Clean-up
      run: rm -rf build